In [ ]:
def find_nearest(V, x):
        """
        Given a list of states V and a query state x, returns the index (row)
        of V such that the steering distance (subject to robot dynamics) from
        V[i] to x is minimized

        Inputs:
            V: list/np.array of states ("samples")
            x - query state
        Output:
            Integer index of nearest point in V to x
        """
        #raise NotImplementedError("find_nearest must be overriden by a subclass of RRT")
        query_state_x = np.array(x)
        states_V = np.array(V)
        dist = np.linalg.norm(states_V-query_state_x, axis=1)
        nearest_index = np.argmax(dist)
        return nearest_index

In [19]:
def rescale_V(V, om, V_max, om_max):
    """
    This function computes V_tilde, given the unconstrained solution V, and om.
    Inputs:
        V: vector of velocities of length T. Solution from the unconstrained,
            differential flatness problem.
        om: vector of angular velocities of length T. Solution from the
            unconstrained, differential flatness problem.
    Output:
        V_tilde: Rescaled velocity that satisfies the control constraints.

    Hint: At each timestep V_tilde should be computed as a minimum of the
    original value V, and values required to ensure _both_ constraints are
    satisfied.
    Hint: This should only take one or two lines.
    """
    ########## Code starts here ##########
    V_candidates = np.stack((V,np.ones(len(V)).astype(float)*V_max, om_max*V/om))
    print("V",V)
    print("V_candidates", V_candidates)
    print("V_max", V_max)
    print("om_max", om_max)
    
    V_tilde_indexes = np.argmin(np.absolute(V_candidates),axis=0)
    
    print("V_tilde_indexes", V_tilde_indexes)
    
    V_tilde = V_candidates[V_tilde_indexes, np.arange(len(V))]
    
    print("V_tilde", V_tilde)
    ########## Code ends here ##########
    return V_tilde

In [22]:
V = np.random.uniform(low=-10,high=10,size=4)
om = np.random.uniform(low=-5,high=5,size=4)
V_max = 5
om_max = 1.0


In [23]:
rescale_V(V, om, V_max, om_max)

V [-0.37091501  9.02651829  7.10857233 -3.81346982]
V_candidates [[ -0.37091501   9.02651829   7.10857233  -3.81346982]
 [  5.           5.           5.           5.        ]
 [  0.20746858 -13.05028852   2.19675396   1.02802064]]
V_max 5
om_max 1.0
V_tilde_indexes [2 1 2 2]
V_tilde [0.20746858 5.         2.19675396 1.02802064]


array([0.20746858, 5.        , 2.19675396, 1.02802064])

In [ ]:
import numpy as np
V = np.random.rand(1000,2)
V

x = (0.25, 0.45)
x

find_nearest(V, x)

In [ ]:
import numpy as np

In [ ]:
np.random.uniform(low=[0,30],high=[10,40],size=2)

In [ ]:
x = [1,2,3,4,5]

In [ ]:
np.flip(x)

In [4]:
t_init = 0
t_f = 10
dt = 
np.arange(t_init, t_f, dt)

array([0, 5])

In [2]:
import numpy as np

In [5]:
np.linalg.norm([2,3])

3.605551275463989

In [6]:
np.sqrt(2**2 + 3**2)

3.605551275463989

In [24]:
x_d = np.ones(5)
y_d = np.ones(5)

In [25]:
xy_d = np.stack([x_d, y_d]).transpose()
theta_d = np.arccos(x_d/np.linalg.norm(xy,axis=1))

In [26]:
theta_d

array([0.78539816, 0.78539816, 0.78539816, 0.78539816, 0.78539816])

In [10]:
import numpy as np
x = np.ones(5)*10
y = np.ones(5)*2
max_x = 10
max_y = 3
candidates = np.vstack((x,y,max_x*x/y))
temp = np.argmin(candidates,axis=0)

In [11]:
candidates

array([[10., 10., 10., 10., 10.],
       [ 2.,  2.,  2.,  2.,  2.],
       [50., 50., 50., 50., 50.]])

In [12]:
temp

array([1, 1, 1, 1, 1])

In [4]:
candidates[np.arange(len(a)), np.arange(candidates.shape[1])]

2

In [2]:
import numpy as np

In [5]:
np.clip([2,3,4,6,3,1,2], -2 ,2 )

array([2, 2, 2, 2, 2, 1, 2])

In [10]:
def wrapToPi(a):
    if isinstance(a, list):    # backwards compatibility for lists (distinct from np.array)
        return [(x + np.pi) % (2*np.pi) - np.pi for x in a]
    return (a + np.pi) % (2*np.pi) - np.pi

In [7]:
np.pi

3.141592653589793

In [8]:
2*np.pi

6.283185307179586

In [16]:
wrapToPi(3.15)

-3.133185307179586

In [17]:
np.sin(100)

-0.5063656411097588

In [21]:
alpha = 5

x1 = np.cos(alpha)
x2 = np.cos(wrapToPi(alpha))

print("x1:", x1)

print("x2:", x2)

x1: 0.2836621854632263
x2: 0.28366218546322647


In [ ]:
V_candidates = np.stack((V,np.ones(len(V)).astype(float)*V_max, om_max*V/om))

In [1]:
x = [5,1,10,15,0,5,7]

In [5]:
import numpy as np
np.argmin(x)

4